steps:
  # Construcción y subida de la imagen para Order Service
  - id: 'Build First Application'
    name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args: ['-c', 'cd ./backend/order && npm install --legacy-peer-deps && npm run build']

  - id: 'Build Docker Image for First Application'
    name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--tag'
      - 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore/msa-order-img:$COMMIT_SHA'
      - '-f'
      - './backend/order/Dockerfile'
      - './backend/order'

  - id: 'Push Order Service'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore/msa-order-img:$COMMIT_SHA']

  - id: 'Check and Update Instance'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if gcloud compute instances describe msa-joyasperu-order --zone=us-central1-a; then
          echo "Instance exists. Stopping it first..."
          gcloud compute instances stop msa-joyasperu-order --zone=us-central1-a
          
          echo "Updating container..."
          gcloud compute instances update-container msa-joyasperu-order \
            --zone=us-central1-a \
            --container-image=us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore/msa-order-img:$COMMIT_SHA \
            --container-env=PORT=4002,HOST=https://backend.perujoyas.com,MONGO_DB_URI=mongodb+srv://vady123:vady123!@proyectos.bihss.mongodb.net/,PAYPAL_CLIENT_ID=Af1t4hGpVKagzJ4NRRe0Ej-iS2q1AUzEGdVD1uVRCZXUov9j0sU7gNb3GjOI2m7QVjXwKwKd4eHt19eX,PAYPAL_CLIENT_SECRET=EJ3b8ceL7lUd19hpTrORXzjrWUjq2DESi5mVNnLASO8JyydNS_p7U7aJFlusgdvWjxLHZQklqM4TrITt,PAYPAL_API_BASE_URL=https://api-m.paypal.com
          
          echo "Starting instance again..."
          gcloud compute instances start msa-joyasperu-order --zone=us-central1-a
        else
          echo "Instance does not exist. Creating new instance..."
          gcloud compute instances create-with-container msa-joyasperu-order \
            --container-image=us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore/msa-order-img:$COMMIT_SHA \
            --zone=us-central1-a \
            --machine-type=e2-micro \
            --boot-disk-size=10GB \
            --network=default \
            --network-tier=STANDARD \
            --tags=http-server,https-server \
            --restart-on-failure \
            --container-env=PORT=4002,HOST=https://backend.perujoyas.com,MONGO_DB_URI=mongodb+srv://vady123:vady123!@proyectos.bihss.mongodb.net/,PAYPAL_CLIENT_ID=Af1t4hGpVKagzJ4NRRe0Ej-iS2q1AUzEGdVD1uVRCZXUov9j0sU7gNb3GjOI2m7QVjXwKwKd4eHt19eX,PAYPAL_CLIENT_SECRET=EJ3b8ceL7lUd19hpTrORXzjrWUjq2DESi5mVNnLASO8JyydNS_p7U7aJFlusgdvWjxLHZQklqM4TrITt,PAYPAL_API_BASE_URL=https://api-m.paypal.com \
            --address=joyasperu-ip
        fi


timeout: '1400s'
logsBucket: 'gs://joyasperu-dev-app-cloud-build'
serviceAccount: '1094025365695-compute@developer.gserviceaccount.com'