steps:
  # Construcción y subida de la imagen para Auth Service
  - id: 'Build Order Service'
    name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--tag'
      - 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore/msa-order-img:$COMMIT_SHA'
      - '-f'
      - './backend/order/Dockerfile'
      - './backend/order'
      
  - id: 'Push Order Service'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore/msa-order-img:$COMMIT_SHA']
  
  # Desplegar en Compute Engine
  - id: 'Deploy to Compute Engine'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instances create-with-container msa-joyasperu-order \
        --container-image=us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore/msa-order-img:$COMMIT_SHA \
        --zone=us-central1-a \
        --machine-type=e2-micro \
        --boot-disk-size=10GB \
        --network=default \
        --tags=http-server,https-server \
        --restart-on-failure

timeout: '1600s'
  # Install dependencies and build
#  - name: 'gcr.io/cloud-builders/npm'
#    entrypoint: 'bash'
#    args: ['-c', 'cd backend/notification && npm install && npm run build:function']
#
#  - name: 'gcr.io/cloud-builders/npm'
#    entrypoint: 'bash'
#    args: ['-c', 'cd backend/shop && npm install && npm run build:function']
#
#  - name: 'gcr.io/cloud-builders/npm'
#    entrypoint: 'bash'
#    args: ['-c', 'cd backend/auth && npm install && npm run build:function']

  # Deploy Cloud Function
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    entrypoint: 'gcloud'
#    args:
#      - 'functions'
#      - 'deploy'
#      - 'notificationService'
#      - '--region=us-central1'
#      - '--memory=512MB'
#      - '--allow-unauthenticated'
#      - '--trigger-http'
#      - '--runtime=nodejs20'
#      - '--source=./backend/notification/dist'
#      - '--set-env-vars=MONGO_DB_URI=mongodb+srv://vady123:vady123!@proyectos.bihss.mongodb.net,NODEMAILER_USER=egalindoa@uni.pe,NODEMAILER_PASS=alhl uyov wnxt zgfe'
#      - '--entry-point=notificationHandler'
#
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    entrypoint: 'gcloud'
#    args:
#      - 'functions'
#      - 'deploy'
#      - 'shopService'
#      - '--region=us-central1'
#      - '--memory=512MB'
#      - '--allow-unauthenticated'
#      - '--trigger-http'
#      - '--runtime=nodejs20'
#      - '--source=./backend/shop/dist'
#      - '--set-env-vars=MONGO_DB_URI=mongodb+srv://vady123:vady123!@proyectos.bihss.mongodb.net'
#      - '--entry-point=shopHandler'
#  
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    entrypoint: 'gcloud'
#    args:
#      - 'functions'
#      - 'deploy'
#      - 'authService'
#      - '--region=us-central1'
#      - '--memory=512MB'
#      - '--allow-unauthenticated'
#      - '--trigger-http'
#      - '--runtime=nodejs20'
#      - '--source=./backend/auth/dist'
#      - '--set-env-vars=MONGO_DB_URI=mongodb+srv://vady123:vady123!@proyectos.bihss.mongodb.net,TOKEN_TIMEOUT=3600,TOKEN_SECRET_WORD=Santiago123!'
#      - '--entry-point=authHandler'

options:
  logging: CLOUD_LOGGING_ONLY
