steps:
  # Construcción del primer proyecto
  - id: 'Build First Application'
    name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args: ['-c', 'cd ./backend/auth && npm install && npm run build']

  - id: 'Build Docker Image for First Application'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag', 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore:$COMMIT_SHA', '-f', './deploy/Dockerfile', './proyecto1']

  - id: 'Push Docker Image for First Application'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore:$COMMIT_SHA']

  # Construcción del segundo proyecto
  - id: 'Build Second Application'
    name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args: ['-c', 'cd ./backend/shop && npm install && npm run build']

  - id: 'Build Docker Image for Second Application'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag', 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore:$COMMIT_SHA', '-f', './deploy/Dockerfile', './proyecto2']

  - id: 'Push Docker Image for Second Application'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore:$COMMIT_SHA']

  # Desplegar la primera aplicación en Cloud Run
  - id: 'Deploy First Application to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'msa-joyasperu-auth',
        '--image', 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore:$COMMIT_SHA',
        '--port', '4000',
        '--platform', 'managed',
        '--region', 'us-east1',
        '--allow-unauthenticated',  # Asegura exposición pública
        '--ingress', 'all',  # Para exponer a internet
        '--project', 'test',
        '--max-instances', '1'
      ]

  # Desplegar la segunda aplicación en Cloud Run
  - id: 'Deploy Second Application to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'msa-joyasperu-shop',  # Cambiar nombre del servicio
        '--image', 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/joyasperu-apiscore:$COMMIT_SHA',
        '--port', '4001',  # Puerto diferente si se requiere
        '--platform', 'managed',
        '--region', 'us-east1',
        '--allow-unauthenticated',  # Asegura exposición pública
        '--ingress', 'all',  # Para exponer a internet
        '--project', 'test',
        '--max-instances', '1'
      ]

logsBucket: 'gs://joyasperu-dev-app-cloud-build'
serviceAccount: 'terraform-account@oval-crawler-444615-k3.iam.gserviceaccount.com'